version: 1.2
workflows:
  - name: GiraffeDeepVariant
    subclass: WDL
    description: Maps raw short reads from a pair of FASTQs on a pangenome with vg Giraffe and call variants with DeepVariant.
    primaryDescriptorPath: /workflows/giraffe_and_deepvariant.wdl
    testParameterFiles:
      - /params/giraffe_and_deepvariant.json
    branches:
      - giraffedv
    authors:
      - name: Jean Monlong
        email: jmonlong@ucsc.edu
      - name: Adam Novak
        email: anovak@soe.ucsc.edu
      - name: Charles Markello
        email: cmarkell@ucsc.edu
      
